#calculating average marks of an student in 5 subjects
Name=input("Enter your name:")
Class=input("Enter your class:")
Age=int(input("Enter your age:"))
English=float(input("Enter your marks in English out of 100:"))
Maths=float(input("Enter your marks in Maths out of 100:"))
Science=float(input("Enter your marks in Science out of 100:"))
Social=float(input("Enter your marks in Social out of 100:"))
Hindi=float(input("Enter your marks in Hindi out of 100:"))
print("----Student Details----")
print("Name:", Name)
print("Class:", Class)
print("Age:", Age)
print("----Marks Obtained out of 100----")
print("English",English)
print("Maths",Maths)
print("Science",Science)
print("Social",Social)
print("Hindi",Hindi)
print("----Average Score Out Of 100----")
average=(English+Hindi+Social+Science+Maths)/5
print("Average Score:",average)